services:
  db:
    image: postgres:16-alpine
    container_name: choir-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: choirdb
      POSTGRES_USER: choiruser
      POSTGRES_PASSWORD: choirpassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: